### ISSUE TITLE
OnInitialise doesn't work

### ISSUE THREAD

**Issue by MariaShyn** [osano/cookieconsent#389]
```html
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
    window.addEventListener("load", function() {
        var defaultColor =  "#00a0fc";
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": defaultColor,
                    "text": "#ffffff"
                },
                "button": {
                    "background": "#ffffff",
                    "text": defaultColor
                }
            },
            "type": "opt-in",
            "content": {
                "message": 'This website uses cookies to ensure you get the best experience.',
            },
            "position": "top",
            "static": true,
            "onInitialise": function (status) {
                console.log('onInitialise ' + status);
            },
        });
    });
</script>
```
I've never seen onInitialise on my log, but banner opens

**Comment by nobleclem** [comment]
It only gets executed if the cookie has been set.  It's a poor name for the callback.

**Comment by schurig** [comment]
@nobleclem in the documentation it says it's supposed to always be called:

https://cookieconsent.insites.com/documentation/javascript-api/

> **This is called on start up**, with the current chosen compliance. It can be used to tell you if the user **has already consented or not** as soon as you initialise the tool.

**Comment by alexmorleyfinch** [comment]
I agree, the callback is poorly named / documented. These are some great suggestions though. I don't think we should change the name as that would require existing usages to change their code. One  solution is to just call onInitialise all the time (as implied by the name onInitialise).

The function is currently called with the cookie status. I.E. `'allow' | 'deny' | 'dismiss'`. Should it just be called with `undefined` if not selected? I'm not sure how that would affect backwards compatibility.

Maybe it'd just be better to have a new hook altogether that is called if no answer has been given? I think this option is the best for BC, but the naming would probably be confusing, because we'd have an `onInitialise` thats only called when answered, and a `onUnanswered` callback.

Maybe we should just define two new hooks, `onAnswered` and `onUnanswered` and deprecate the `onInitialise` function?

Thoughts?

**Comment by schurig** [comment]
@alexmorleyfinch I agree with your thoughts and like your last suggestion (deprication and using new names).

**Comment by homerjam** [comment]
`onInitialise` is needed to bind the popup instance to a variable so that later we can use the `revokeChoice()` method. Please don't deprecate!

**Comment by TheMangoTrain** [comment]
There's now a onNoCookieLaw hook.

See `thread`.
