### ISSUE TITLE
Decline button not translated

### ISSUE THREAD

**Issue by pklinke** [osano/cookieconsent#419]
The text for the button 'decline' isn't translated anymore on the cookie consent view. In the source it is translated.

1 week ago this still works.

[insites.pdf](https://github.com/insites/cookieconsent/files/2217112/insites.pdf)

**Comment by TomNoblesse** [comment]
The code generator seems to set the property "dismiss" but in de code the property name is "deny" for that buttons' text.

Changing this fixed it for me.

![image](https://user-images.githubusercontent.com/5371523/43519369-77731c44-958f-11e8-9153-031efcc981b4.png)

**Comment by JeePeeNL** [comment]
> The code generator seems to set the property "dismiss" but in de code the property name is "deny" for that buttons' text.

The property depends on the compliance type.
- The '**dismiss**' property is used for compliance type "Just tell users that we use cookies".
- The '**deny**' property is used for opt-in and opt-out.

On the website cookieconsent.insites.com/download/ you can customize the dismiss text, but not the deny text.

They might as well use the same property because there is no compliance type that use both of them.

**Comment by relicmelex** [comment]
This is coming in a PR currently in the dev branch on our next release.
