### ISSUE TITLE
Revokable option get's ignored on init

### ISSUE THREAD

**Issue by Schuer84** [osano/cookieconsent#423]
![image](https://user-images.githubusercontent.com/389703/43131434-50d7be52-8f39-11e8-9ddf-bf9c9f761de5.png)

**Comment by relicmelex** [comment]
Needs more info. Closing ticket for not enough info and staleness.

If you wish this ticket reopened, please use the following form to better help us reproduce your issue:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
