### ISSUE TITLE
dismissOnWindowClick doesn't work on single page app

### ISSUE THREAD

**Issue by eheim** [osano/cookieconsent#427]
I have dismissOnWindowClick set to _true_, but it doesn't get registered for clicks within our single page app. Can this be extended to support that or is there another method that can be called when the route changes?

**Comment by relicmelex** [comment]
@eheim Firstly let me apologize for the delayed response. We have a couple hooks in the library and I encourage you to look into them. However I'm not truly able to understand your issue, because on initialization, this happens:
```
1080: window.addEventListener('click', onWindowClick);
1081: window.addEventListener('touchend', onWindowClick);
```
So really it should be anywhere in the window that is clicked regardless of how it's loaded as long as it's initialized properly.

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
