### ISSUE TITLE
[Test] Add a testing framework

### ISSUE THREAD

**Issue by raul782** [osano/cookieconsent#448]
I wonder if we could add a suite of tests.
I've been trying to test this with CasperJS + PhantomJS, specially the dismissOnScroll and reload, but It seems CasperJS doesn't work with the `window` object.

Is there any other framework that you recommend, I'll start trying with testcafe and puppeteer

**Comment by TheMangoTrain** [comment]
Speaking of testing...

There's also the option to manually test using screenshot services which have geolocation features (as an alternative to spoofing your IP with a VPN).

For example, I can confirm consent prompts don't appear in my location (Canada). Testing with geo-screenshot tools and setting the test location as France or Italy, the screenshot result shows a consent prompt. So as far as I can tell the plugin works. It doesn't account for functionality though.

FYI, I did not get consistent results across the handful of geo-screenshot services I tested. Anyways, there's a bunch of geo-screenshot services. Some free one's work better than other obviously. Some showed no prompt for EU locations that I kind of expected to have prompts (Belgium for instance). So I can't tell are those particular geo-screenshot tools just not doing a correct job (using wrong origin servers) or are there still specific EU countries where cookie laws still don't apply (and the insites cookie consent plugin is reflecting that... or has old law data)?

Maybe it's better just to email my cousin in Finland... "social testing framework".

**Comment by relicmelex** [comment]
We will be adding test suites in v4 as that's when we will have time to refactor... among many things into more than one file 😆!

If you're looking for JavaScript test frameworks though. Mocha & Jasmine are among the two most popular. There are specific ones though if you're using a framework like Angular or ReactJS.

Also in v4 look for instances instead of attaching to the window object 😡 😄

Thanks for your contributions!
