### ISSUE TITLE
Enhancement Suggestion: Demo 6: Automatically detect country code from users location

### ISSUE THREAD

**Issue by bgildea** [osano/cookieconsent#463]
A suggestion related to Demo 6. A explicit new location demo where it reads the location country code automatically from the browser headers and changes the banner to the correct law. That would be really helpful. It could be tested using a VPN or Operas built in VPN. Thanks.

**Comment by arlogilbert** [comment]
@bgildea you can add this capability, and if you'd like to submit a PR with this capability we will accept it, but we would not add this to the configurator because there is too much room for abuse. 

Geolocation in the browser is something we view as a potential privacy issue. As well there is no clear legal precedent about whether a web site owner can require the user to consent to location tracking in order to provide cookie options.

Across the web we see geolocation being abused and suspect that in the future, browser makers may restrict this capability, remove it, or modify it's functionality.

Finally, the kind of geolocation provided by browsers is not required to make decisions about cookie consents. Knowing which country that an end-user is currently located in is sufficient and can be identified with high accuracy using less invasive methods.
