### ISSUE TITLE
revoke button is appears at anytime

### ISSUE THREAD

**Issue by dolav** [osano/cookieconsent#465]
My cookieconsent panel type should be opt-in and I don't want to have the revoke button.
My configuration including the next attributes:
```
type: 'opt-in',
revokable: false,
law: { regionalLaw: false }
```
[This](https://github.com/insites/cookieconsent/blob/b54a9535f644c865750f2f84c758d584ce3fb2c5/src/cookieconsent.js#L1657) should make sure that revokable value stays false.
For some reason, the revoke button is displayed on the screen.

**Comment by thexmanxyz** [comment]
@dolav possible duplicate https://github.com/insites/cookieconsent/issues/245

**Comment by dolav** [comment]
Just to make sure.
The code I wrote above doesn't suppose to cancel the revokable button?
As you mention in your [issue](https://github.com/insites/cookieconsent/issues/245), the documentation saying:

> If false, then we only enable the popup if the country has the cookie law. We ignore all other country specific rules.

This means that if `law: { regionalLaw: false }` then revokable button law should be ignored. In [this](https://codepen.io/dolav/pen/qJOLPP) small example, you can see the opposite.
 
My analyze:
- From one hand, this [code snippet](https://github.com/insites/cookieconsent/blob/b54a9535f644c865750f2f84c758d584ce3fb2c5/src/cookieconsent.js#L1657) looks like you take care of this behavior and check the regionalLaw.
```
      if (this.options.regionalLaw) {
        if (country.revokable) {
          // We must provide an option to revoke consent at a later time
          options.revokable = true;
        }
        ...
      }
```
- But, from the other hand, when CookiePopup is called, then [applyRevokeButton](https://github.com/insites/cookieconsent/blob/b54a9535f644c865750f2f84c758d584ce3fb2c5/src/cookieconsent.js#L1083) also run and [change](https://github.com/insites/cookieconsent/blob/b54a9535f644c865750f2f84c758d584ce3fb2c5/src/cookieconsent.js#L1085) the revokable value without check regionalLaw. 
```
    function applyRevokeButton() {
      // revokable is true if advanced compliance is selected
      if (this.options.type != 'info') this.options.revokable = true;
      ...
    }
```

**Comment by TheMangoTrain** [comment]
How can we know the status of location services, whether failed or success? Let's say the included free services all fail, and the default consent is shown. How do we know if the issue was due to location look-up failure or something else in our script? Just a console.log somewhere would be nice.

**Comment by relicmelex** [comment]
@dolav Sorry for the delayed reply.

The reason for the `!= "info"` is in any case where the use ends up with a cookie they're required to be able to revoke that permission. Info would be the only use case where there's no permission granted to revoke.

This is expected behavior.

**Comment by thexmanxyz** [comment]
@dolav I also forgot on answering on this issue. The problem with that configuration value is, that the documentation doesn't reflect what is really going on. As I wrote in #245, the documentation is simply wrong. `regionalLaw` only influences the `dismiss...` parameters and `revokable` but has no effect on the popup (which the docs wrongly indicates). 

> If set true, revoke button is displayed every time. If false, revoke button is only displayed for advanced compliance options (opt-in and opt-out) and in countries that require revokable consent. The latter can be disabled by _regionalLaw _below.

It's quite some time and I'm not 100% sure what's going on in your case. But the above explanation of the `revokable` parameter should clear things up. Also what you already found out and what @relicmelex  said. The `revokable` is always forced to `true` except for `type: info` so this probably is an expected behaviour. To sum things up you can force `revokable` to be shown but you can't the other way around disable it completely. I hope I'm not telling BS here but that should be the actual culprit.

**Comment by thexmanxyz** [comment]
@dolav As an additional information. If you set `regionalLaw: true` it will override the manually set `revokable` button in dependence of the service. I think the whole behaviour around that `revokable` parameters needs some sort of rework because `revokable` actually only affects `type: info` and has no other effect at all. Which kind of makes it obsolete and misleading.

**Comment by thexmanxyz** [comment]
@dolav As an additional information. If you set `regionalLaw: true` it will override the manually set `revokable` button in dependence of the service.

@relicmelex I think the whole behaviour around that `revokable` parameters needs some sort of rework because `revokable` actually only affects `type: info` and has no other effect at all on other types. Which kind of makes it obsolete and misleading. In my opinion it should take effect independently of the `type` parameter even if it was intended otherwise in the first place.

**Comment by relicmelex** [comment]
@thexmanxyz Andreas, that's why I'm here haha. I've been brought into Osano specifically to rework, enhance and grow this project to respect the amount of users we already support out there in the wild wild web ( That's what WWW stands for yes? )

To your point though we are working not only on these issues but resolving them the right way. Just hacking the code base for a 'fix' when really what we're looking at is a breaking change, a refactor or sometimes a new feature that should really be implemented by itself and not as an extension of the current code.

What this means is some times looking at an issue like this here and realizing we need to keep better track of our docs as opposed to making code changes. This is really important for many reasons top of which is clarity and understanding, and simply put, we failed here.

The first step is for us to try and update our docs where we can, and in the future I intend to pull the docs into the repo so it's easier for the community to not only have access to them but be able to contribute there as well as in the code.

To conclude and make sure you understand the reason for closing this issue is our docs are wrong yes, [we will work on that](https://github.com/osano/cookieconsent/issues/568), but this is intended behavior because of the way the laws work not how the parameters could work, or how we could get clever in the code to make things come and go. It's about making sure they have the option to revoke the permission given. If you'd like another way to setup the ability to revoke we'd love those suggestions, and even I have some ideas on how we can do that already based on your comments here.

And a suggestion to go with that; You could always ( within the law ) create a trigger that changes the HTML value of that element based on a click or something... ;)
