### ISSUE TITLE
Feature suggestion: Appear on scroll and/or delayed appearance

### ISSUE THREAD

**Issue by zamirkhan** [osano/cookieconsent#471]
Unless I'm mistaken and this is currently supported, it would be nice if when the user visits a site, they get to experience it, at least for the first few seconds as pristine (without the cookie banner). Then, if they started scrolling, or after a developer-specified delay (e.g. on the order of 5 seconds or less), the cookie banner would appear. I'm not sure if this is against the cookie law though.

**Comment by thexmanxyz** [comment]
@zamirkhan You can implement that yourself if you want, probably something that doesn't would make its way into the API because of deprecation state in the future see also #409 

You could easily do something like this what would delay for 5000 milliseconds:

```Javascript
setTimeout(function(){ window.cookieconsent.initialise({...},5000)});

```

There is also straight forward ways to achieve something similiar on a scroll event, no need to implement something like this within the API.

**Comment by thexmanxyz** [comment]
test

**Comment by thexmanxyz** [comment]
test2

**Comment by thexmanxyz** [comment]
@zamirkhan Take also a look on #409 IDK if this will find its way into the API because of the current state. However you can easily implement the requested functionality yourself and wrap it around the original configuration code of the API. If you want do delay the dialog for e.g. 5000 milliseconds you could easily do something like this:

```Javascript
setTimeout( function(){ window.cookieconsent.initialise({...}) }, 5000);
```
For the sake of simplicity I didn't include any `.initialise()` configuration parameters.

There are also straight forward ways to simple trigger the dialog on scrolling e.g. after some scrolling time with an event. For more information take a look on [this thread](https://stackoverflow.com/questions/22913305/how-to-trigger-event-after-i-scroll-a-page-certain-amount-in-pixels-from-the-top)

No need to implement something like this within the API. Simply load the cookie consent dialog after some amount of scrolled pixels.

**Comment by wargo32** [comment]
You should do this in reverse way - hide info when user tries to use your website.

**Comment by relicmelex** [comment]
@zamirkhan Thanks for this question. So after looking at what you were asking and the suggestion because there is no way to determine how long a user will be on the site before it loads, legally speaking it should be the first thing they see in some manner. This law is obnoxious to the experience some times, but it can be mitigated with style and this is why we offer so much extension to the templates and styles available so you can make it the least intrusive to the user's experience. 

@wargo32 it does do that, `dismissOnScroll: true` and `dismissOnWindowClick: true`
