### ISSUE TITLE
dismiss button does not work with most simple compliance type

### ISSUE THREAD

**Issue by smurfer** [osano/cookieconsent#476]
Hi, I am not an expert, but have used the 1.01 version before which worked. For the version 3.1.0, just copying the source as given by the wizard and using "Just tell users that we use cookies" does not work. The "Got it" button does remove the message. However, clicking on it results in the message not being shown the next time the page is loaded.

**Comment by relicmelex** [comment]
@smurfer Are you still experiencing this issue? If so please use the following format for letting us know how to reproduce the bug: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by relicmelex** [comment]
Stale. Closing issue. 

@smurfer We're working on updating our docs, they had a couple bugs in them... should be fixed now.

If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
