### ISSUE TITLE
How to check banner status by cookie name?

### ISSUE THREAD

**Issue by suslikt** [osano/cookieconsent#483]
Good day! I have 2 banners, each with its own cookie name. 
`window.cookieconsent.initialise({
  cookie: {
    name: "22222222"
  }`
The problem is that the second banner should appear only if the first one is in the "dismiss" status. How to check status of first banner by name?

I tried to do something using `onInitialise: function(status)` , but nothing happened.

Thx

**Comment by courtneyaschwartz** [comment]
Different cookie names are not enough. `window.cookieconsent` is still only 1 object namespace still, not 2. 

CC would need a feature like:

https://www.w3schools.com/jquery/jquery_noconflict.asp
https://github.com/js-cookie/js-cookie#namespace-conflicts
https://developers.google.com/analytics/devguides/collection/analyticsjs/renaming-the-ga-object

Currently, CC can handle only 1 banner and cookie. It will clobber itself if you try to initialize 2 times:
https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L2
https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L1742

Even if you initialize 2 object names, each banner won't have a unique HTML element ID:
https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L296
so their event handlers can't target a specific banner:
https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L373

**Comment by relicmelex** [comment]
@suslikt unfortunately @courtneyaschwartz is correct. CookieConsent is not set for multiple instances in a single page. Can I ask what your use case is for this because maybe the current event hooks are enough for you as this library doesn't handle disallowing cookies for a domain per se, it's a lib that has a view layer and offers some event hooks with statuses tied to a cookie ( within it's own regulations )?

Maybe we can add this as a feature in v3.x somewhere along the line, but in v4 we will be using objects and constructors so you will be able to have as many as you want.

**Comment by relicmelex** [comment]
Feature in coming version. ( ~v4 or ~v5 ) as it introduces breaking changes. Closing Issue.
