### ISSUE TITLE
Disable pop-up on mobile view

### ISSUE THREAD

**Issue by niccoX** [osano/cookieconsent#484]
When you accept or reject the policy, on mobile view there will still be a pop-up box attached to the bottom of the page, and you can't remove it. How do you remove it?

This is only if you have the reject option enabled. Without it, when you accept your policy the banner will disappear for good.

**Comment by easingthemes** [comment]
JS: use `revokable` option. 
https://cookieconsent.insites.com/documentation/javascript-api/#revoke_options
```
revokable: false
```
CSS: Hide the button for some sizes:
```
@media screen and (max-width: 768px) {
  .cc-revoke {
    display: none;
  }
}
```

**Comment by nicolasbadia** [comment]
For me, the popup stay visible even if `revokable` is set to `false`...

**Comment by relicmelex** [comment]
Acceptable answers if a bit hackey and no reply from OP in 6+ mo. Closing.

If this needs to be reopened, please use the following form so we may better assist you:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
