### ISSUE TITLE
Boolean value for dismissOnScroll does not work.

### ISSUE THREAD

**Issue by aioobe** [osano/cookieconsent#494]
The [documentation](https://cookieconsent.insites.com/documentation/javascript-api/) says

> `dismissOnScroll` (boolean | integer) 
> Default: `false`
> Set value as scroll range to enable.

But it only seems to work when I set an integer.

In the code I can only see

    var scrollRange = this.options.dismissOnScroll;
    if (typeof scrollRange == 'number' && scrollRange >= 0) {
      ...

and nowhere can I find a code path that deals with the case when `dismissOnScroll` is set to true.

**Comment by courtneyaschwartz** [comment]
@aioobe Documentation could be more accurate. `dismissOnScroll: true` won't work.

Look again ~ line 1032-1033.  It explains why :
`if (typeof scrollRange == 'number')`

If you pass a Boolean `true` (or `false` or `alpacas` or any other non-integer), then the `typeof` condition evaluates to `false`; scroll-to-dismiss won't run. 

Corollary: Any int here is the logical equivalent of `true`. (That's why you don't literally need `dismissOnScroll = true`.)

And 2 separate variables (Boolean `dismissOnScroll` and int `scrollRange`) is not efficient notation, anyway... Non-`strict` JavaScript isn't a strongly typed language. So it smartly combines both types into 1 variable.

Valid values really are:
- number (aka `true` + number of pixels that the user must scroll to dismiss)
- anything else (aka `false`)

Pretend the doc says:

> `dismissOnScroll` (false | integer)
> Default: `false`
> To disable, set to "false". To enable, set to the number of pixels a user must scroll vertically in order to trigger the dismiss.

**Comment by relicmelex** [comment]
Closing because there was no requested behavior that is different from current behavior, and any confusion was settled. ( & 6+ months )

@courtneyaschwartz Thanks for the suggested edit. I think in the future we will be putting our docs in with our code so that you can PR stuff like that.

**Comment by relicmelex** [comment]
@arlogilbert we should probably use that update to the docs.

**Comment by courtneyaschwartz** [comment]
@relicmelex No problem. I would definitely PR if I could... Save you the time to copy+paste.

**Comment by aioobe** [comment]
I assumed the following interpretation:

`false`: inactivated
`true`: dismiss on _any_ scroll. That is, _no_ threshold on how far you must scroll.
`number`: Set a threshold for how far to scroll before dismiss.

Maybe it's the case that >= 1 pixel is equivalent to any scroll at all, but it's not obvious to me, considering that you can zoom on a page.

To be clear, the requested behavior is to let `true` mean _any_ scrolling. The benefits as I see it, are

- There are fewer invalid (but correctly typed) configuration options
- It allows you to enable dismiss on scroll without settling with a scroll threshold
- Less confusing imo ("Do you want to dismiss on scroll?" -- "Yes (`true`).")
- Also, it's presumably backward compatible, since `true` was invalid before.

**Comment by relicmelex** [comment]
@aioobe Thanks for the input!

The reason for there to not be a `true` is that it's an incomplete thought or a confusing use of a single property with multiple type expectations. Setting event values of 'undefined' is essentially false. So setting false in this sense just doesn't change anything because what's actually happening is a type check. This type check looks for a number, so undefined, true, false, or anything other than a number fails. This conditional also means you can think of '-1' as false, which is a common programming flag concept. To complete the thought without having another property to keep the discipline of the event set to a single variable we're essentially always using a distance and a distance less than < 0 sets the event to not trigger ('off') and anything > 0 ( because any scroll event distance is always > 0 ) fires the event. Because this is implied, it's important to give the option of 'when'. So when setting to > 0 you can customize the 'when' without a special `dismissOnScrollDistance` property as well.

**Comment by aioobe** [comment]
> The reason for there to not be a `true` is that it's an incomplete thought

I disagree. I want the notification to be dismissed on scroll. That's it. I argue that it is clear that this means _any_ scroll, and that this thought is "complete".

It's nice to have a way to set a scroll threshold, and a threshold implies some sort of dismiss on scroll "truthness", so having a single parameter for this configuration makes sense, but I don't buy that `true` would be underspecified. In fact I stand by my previous message that it's _surprising_ that `true` is illegal considering the parameter...

A) ...has a "boolean sounding" name (it's called `dismissOnScroll` and not `dismissOnScrollDistance`) and

B) ...has `boolean` listed as an acceptable type.

> anything > 0 ( because any scroll event distance is always > 0 ) fires the event

So, going back to my original intent of configuring it so that it's dismissed on _any_ scroll (I doubt this is a rare use case) what should I put? 1? I tested zooming in on a page in Firefox, and I can indeed scroll 0.9. Maybe 0.1? 0.00001? To me this looks a bit ridiculous in my conf, when all I wanted to express was `dismissOnScroll` -- `yes`.

In my opinion a single parameter is a good choice. Having `boolean | number` is a good choice. Have a boolean sounding name is reasonable. But disallowing `true` simply doesn't make sense.

**Comment by relicmelex** [comment]
@aioobe On a breaking change we will probably change the property name to `dismissOnScrollDistance` as you suggested to reduce confusion and change the docs to represent a '-1' as "off".
