### ISSUE TITLE
 Make CookieConsent Status parameterable 

### ISSUE THREAD

**Issue by johnbyronent** [osano/cookieconsent#495]
Current Implementation doesn't support the changing of the cc.status values.

The Code always takes the Object.keys(cc.status) instead of the actual value by using Object.values(cc.status)

**Comment by jerone** [comment]
Ref https://github.com/insites/cookieconsent/pull/456

**Comment by relicmelex** [comment]
@johnbyronent What's your use case for needing to modify these. If I'm not mistaken these are just internal values only ever exposed in the `onStatusChange` callback. And being that they're really meant to be constants and just a value for reference in a call back I'm not sure what value would be in changing them or having them be customizable because they will always represent the same thing.

**Comment by relicmelex** [comment]
Closed, referencing PR #496 and [comment](https://github.com/osano/cookieconsent/pull/496#issuecomment-513573729)
