### ISSUE TITLE
Adding Google Events Click Tags to Cookie Conset

### ISSUE THREAD

**Issue by mkeez** [osano/cookieconsent#508]
Is it possible to add Google Analytics click event tags into the Cookie Consent widget? We'd like to track counts of users who click on one or the other of our options.

**Comment by jhabdas** [comment]
See that's the funny thing. EU rules stipulate consent must be obtained prior to collecting personal data like a u, so you'd only ever be able to know how many people opted in.

Furthermore this library makes an ajax call to MaxMind which actually contains PII therefore rendering the geofencing added in v2 in violation of the regs.

**Comment by jhabdas** [comment]
See that's the funny thing. [Privacy by design](https://eugdpr.org/the-regulation/gdpr-faqs/) stipulates consent _must_ be obtained _prior to_ collecting personal data as GA does.

Furthermore v2 of this library [makes an external call to MaxMind](https://github.com/insites/cookieconsent/issues/504) which, if you read their [Privacy Policy](https://www.maxmind.com/en/privacy-policy) may be used for marketing purposes—therefore rendering users of v2 out of compliance before users even have the chance to consent.

**Comment by jhabdas** [comment]
See that's the funny thing. [Privacy by design](https://eugdpr.org/the-regulation/gdpr-faqs/) stipulates consent _must_ be obtained _prior to_ collecting personal data as GA does.

Furthermore v3 of this library [makes an external call to MaxMind](https://github.com/insites/cookieconsent/issues/504) which, if you read their [Privacy Policy](https://www.maxmind.com/en/privacy-policy) may be used for marketing purposes—therefore rendering users of v3 out of compliance before users even have the chance to consent. But I get the sense people using this library don't really care much about the privacy of their users otherwise they would've done their homework.

**Comment by courtneyaschwartz** [comment]
Yes, it's possible @mkeez  

Depending on what you mean by "other options", it might be a compliance violation. So be careful. But the "ghost" makes it sound like it's always a Catch-22, and there's never a legitimate use case... It's not.

- Check your Google Analytics settings. It _doesn't_ always collect personal info (PII) as defined by GDPR... If you don't, and the banner is only for info, then you could init GA during CC's `onInitialize` event. But if you do collect PII, then hook into `onStatusChange` where `didConsent == true` instead. Then you're tracking only consenting users. Obviously **don't** track PII on users who click "Deny".
- Use `location: false` and `regionalLaw: false` . This avoids 3rd party privacy issues w/ the call to MaxMind/other external location services. Besides, EU citizens could be visiting another country. Safer IMO to show it everywhere.

For example, you might init GA virtual pageviews as soon as they click "OK"/"Allow" (not the CC `onInitialize`/next page load event) in order to gather usability data for Ajax controls.

More info/examples:
https://cookieconsent.insites.com/documentation/disabling-cookies/ (CC onStatusChange)
https://support.google.com/analytics/answer/3123662?hl=en (About User-ID)
https://support.google.com/analytics/answer/2799357?hl=en (About Demographics and Interests)
https://support.google.com/analytics/answer/2763052?hl=en (About IP Anonymization)
