### ISSUE TITLE
When changing Textcolor only reflink changes color

### ISSUE THREAD

**Issue by mavoni2701** [osano/cookieconsent#510]
Whenever i try to change the color by colorcode, for example:

```
 "palette": {
    "pop up": {
      "background": "#aa0000",
      "text": "#000000"
    },
    "button": {
      "background": "#ff0000"
    }
  }
```

 only the reflink changes the color.
Is it maybe because of my css file?

**Comment by mavoni2701** [comment]
![screenshot_1](https://user-images.githubusercontent.com/47755988/52970508-4a963a80-33b4-11e9-9ac2-f21ba30b98e6.png)

**Comment by relicmelex** [comment]
@mavoni2701 Sorry for the delay, this library changed hands a while back and we're just ramping up support again.

In the 'palette' block you have `"pop up"`. This should be one word `popup`. Please let me know if this fixes it for you, or if you've already figured it out as it's been a couple months since you posted this issue.

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.
