### ISSUE TITLE
Set cookieconsent_status cookie value manually

### ISSUE THREAD

**Issue by sarinkarma** [osano/cookieconsent#511]
During onNoCookieLaw callback hook i wanted to set the value of cookieconsent_status to allow manually.
onNoCookieLaw: function() {
    this.setStatus(cookieconsent.status.allow);
},
But it doesnt seem to change the value from undefined.
Any help will be appreciated.

**Comment by relicmelex** [comment]
@sarinkarma this only fires when `if (!country.hasLaw) {` which means your locations has to have that flag generated to fire. Try setting the `location` flag in the options too `true`.



Can you please put your entire config here, as well as some steps to reproduce so I can look into this some more and see if it's something that should be done or if there's a better way to do what you're attempting to do.

**Comment by relicmelex** [comment]
Stale. Closing issue. If this comes back up please open a new issue in the 'bug' category as it will ask you for more detail to help us better resolve the issue.

@sarinkarma If you open a new issue make sure you use the form to better describe what you're trying to do outside of the context of the code specifics so maybe I can point you in the right direction of how to solve the specific problem.

Also: `onNoCookieLaw` is not a supported callback, that's why it's not in the docs, it's not really a proper lifecycle method and doesn't give you access to the object so `this` is actually the `Law` Object for the plugin.
