### ISSUE TITLE
Dismiss button <a> tag is not properly formatted to work for Enter key

### ISSUE THREAD

**Issue by alexadevoe** [osano/cookieconsent#512]
I saw the reply on a previous issue and I have a simple fix for this:
https://github.com/insites/cookieconsent/issues/453#issue-355999452

All you need to do is add href="#" to the dismiss button <a> tag and the Enter key will automatically work --- this is very important in order to be WCAG 2.0 / WCAG 2.1 compliant and make this Dismiss button accessible to all users and it will work with the "Enter" key.

**Current <a> tag:**
`<a aria-label="dismiss cookie message" role="button" tabindex="0" class="cc-btn cc-dismiss">Accept</a>`
**New <a> tag:**
`<a href="#" aria-label="dismiss cookie message" role="button" tabindex="0" class="cc-btn cc-dismiss">Accept</a>`

I'm a software engineer and I can help and contribute to making this plugin even better - it's already awesome!
Please contact me if you like me to help in any way.

**Comment by relicmelex** [comment]
@alexadevoe Alexa, we don't want to capture the enter key by default in the library. There are numerous reasons for this one of which a lot of Web Apps will have their own focus and we don't want our plugin to introduce breaking changes into current apps. The issue you linked below would be the proper way of handling this especially because there is no link, and we don't want google to start indexing that link as a part of people's site map. I could go on, but I hope this helps you understand why adding it as a part of the library isn't something we would do by default. However we may wrap our own even listener around it later and add a property to the config like `allowOnKeyPress( keyCode )` as a feature in the future, so I'll mark this as a feature request.

**Comment by relicmelex** [comment]
Issue #571 is for the feature request and allows this to be closed.
