### ISSUE TITLE
Programmatic open

### ISSUE THREAD

**Issue by char0n** [osano/cookieconsent#517]
Is there a possibility to open cookieconsent panel programatically when I already closed it and `window.cookieconsent` is available to me ? I want to have my own control which will triggers the Popup when clicked.

Thank you

**Comment by char0n** [comment]
Found it https://github.com/insites/cookieconsent/blob/master/examples/example-7-javascript-api.html

Thanks

**Comment by relicmelex** [comment]
Issue resolved - [Documentation](https://github.com/osano/cookieconsent/issues/517#issuecomment-469042404)

**Comment by char0n** [comment]
Thanks, but the link to `Documentation` leads to my comment. Is that right ?

**Comment by relicmelex** [comment]
@char0n Yes, I do that just for reference. It lets anyone later looking through it be able to always see the 'closing comment' and being able to have a good reason for the close, while having some sort of link. Here it seems superfluous because it's right there and obvious but I like to keep to a pattern.

Look for new features coming to v3 soon!
