### ISSUE TITLE
Cookie name does not changes

### ISSUE THREAD

**Issue by subhashD** [osano/cookieconsent#521]
Always shows dismiss button. and cookie.name does not changes cookie name

**Comment by solarsilk** [comment]
your code should look something like this:
```
window.cookieconsent.initialise({
        "cookie": {
            "name": 'mycookiename'
        },
        "palette": {
            "popup": {
            "background": "#252e39"
            },
            "button": {
            "background": "#14a7d0"
            }
        },
        "position": "bottom-right",
        "content": {
            "message": "We've recently updated our privacy policy. Continuing to use this site constitutes consent to our revised privacy policy.",
            "dismiss": "I consent",
            "link": "Read the policy",
            "href": "https://xxx"
        }
  })});
```

**Comment by relicmelex** [comment]
This is 3 months old, with no response and no content we're closing the issue. Re-open if you need, but if so please provide:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
