### ISSUE TITLE
only show to eu countries

### ISSUE THREAD

**Issue by drgluk** [osano/cookieconsent#524]
Can anyone advise how to code so this scrip only shows to the EU? I have the following in my head:-

<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  "position": "bottom-left"
})});
</script>

Thanks :)

**Comment by courtneyaschwartz** [comment]
https://github.com/insites/cookieconsent/blob/master/examples/example-6-location.html

**Comment by kgrote** [comment]
The demo example isn't actually very helpful, because obviously in practice the user isn't going to be choosing their location from a dropdown. Would love to see a basic example of how to easily set up the plugin to:

1. Automatically check the user's location
2. Check if that location is in the EU
3. If so, display the banner
