### ISSUE TITLE
Not showing properly on mobile device

### ISSUE THREAD

**Issue by DavidFeliers** [osano/cookieconsent#548]
**Describe the bug**
Everything works how it should be but it is not working on mobile for me. The text is not showing properly.

**To Reproduce**
When it appears on the site.

**Expected behavior**
The text on the banner is not showing properly.

**Screenshots**
See screenshot.

**Desktop (please complete the following information):**
 - Working properly on desktop.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android version 9
 - Browser Chrome
 - Version 74.0.3729.157

![62020104_1032633583608883_5189511853071400960_n](https://user-images.githubusercontent.com/47762032/59065202-762e2980-88ac-11e9-97d4-ef30b0059ee4.jpg)

**Comment by arlogilbert** [comment]
@DavidFeliers this is not a bug with the cookie consent code, the issue is that on your site you have custom CSS that changes the width, height, border, and display properties for all span elements on the site when the window is below a certain width. The span element is a native HTML element, the cookie consent text is just following the CSS rule that was set (see below).

<img width="446" alt="Screen Shot 2019-06-07 at 12 23 21 PM" src="https://user-images.githubusercontent.com/6061697/59100926-58e67300-891f-11e9-959f-b98276bf5ef4.png">
