### ISSUE TITLE
Include "onNoCookieLaw" hook in documentation

### ISSUE THREAD

**Issue by alexmlee** [osano/cookieconsent#575]
**Is your feature request related to a problem? Please describe.**

There is a hook called "onNoCookieLaw", but it's not discussed in the documentation.

**Describe the solution you'd like**

Modify the documentation to include reference and usage to this (and any other hooks)

https://github.com/osano/cookieconsent/issues/332
This issue has mention of the hook

**Comment by relicmelex** [comment]
@alexmlee As it stands, we don't currently officially support the `onNoCookieLaw` callback. If you look through the officially supported callbacks in the documentation, they are all lifecycle style methods or event response methods. `onNoCookieLaw` actually fires after 'onInitialize' which is outside the normal lifecycle and are potentially co-dependant on a 3rd party, or even a custom service definition, which obviously we can't support or respond to issues on because we don't have the ability to affect anything other than this library.

I imagine this was originally placed in for a development hook of the library to handle built-in responses trying to add the country code to the `options`.

( We might move this in the lifecycle, in a different version so it happen in a slightly different manner but supplies the same arguments and fires before 'onInitialize' [ref.v4-Syntax Change] )
