### ISSUE TITLE
Documentation does not include opening/closing the popup via javascript

### ISSUE THREAD

**Issue by skyfox93** [osano/cookieconsent#597]
The documentation does not mention that the initializing function takes a second argument that can be used to assign the popup element to a variable, on which you can call open() and close(), as in [example 7](https://cookieconsent.osano.com/examples/example-7-javascript-api.html)

**Comment by Donsky-Osano** [comment]
@skyfox93 As it stands this isn't a supported exposed feature. This is part of the internal functionality and unfortunately it's a required step if you set 'autoOpen' to false.

We've changed a lot of things in v4 including exposed and sudo private methods ( because JS doesn't allow for truly private properties and methods yet ), so this will help reduce confusion as well as increase the level of support for the features we do expose.

If you're interested look into the dev branch @v4
