### ISSUE TITLE
Works great locally, but "Got it" doesn't not do anything in production.

### ISSUE THREAD

**Issue by dijs** [osano/cookieconsent#602]
**Describe the bug**
When clicking "Got it" on my local server, it creates a cookie and works great. But in production the button does nothing. No errors, no events fired, no cookie. Not sure what to do here.

**To Reproduce**
1. I am using the `npm` module
2. And the getting started code
```js
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  }
});
```
3. Then building (create-react-app) and publishing to production

**Expected behavior**
The "Got it" button should close the pop up and create a cookie in production 

**Desktop (please complete the following information):**
 - OS: Everywhere
 - Browser chrome, safari

**Comment by dijs** [comment]
Update:

I actually do get the "PopupOpen" event. But nothing else.

**Comment by Donsky-Osano** [comment]
Hey @dijs I'm willing to bet that the click event isn't actually getting fired because I can't reproduce this with the steps and config you've posted. There's a chance there's an invisible element covering the pop-up, this would block the click.

Try right clicking the button, or using the element navigator and see what's in front of that button.

**Comment by dijs** [comment]
You were absolutely correct. During my build step, it was render *two* consent forms on top of each other.... Thanks!
