### ISSUE TITLE
Disabling cookies when using the opt in method

### ISSUE THREAD

**Issue by Christoph320** [osano/cookieconsent#610]
Hello,
I know pretty much nothing about js or php. How do I disable the cookies when I use the opt in method? I know there is a code snippet on the Osano site, but in which file should I copy&paste it? And where are the configuration options?

I hope I do not state an issue that was solved before, thank you!

Also: I don't know, how to link a css file to the cookie code. Am I really supposed to put the code inside the body tag in the header.php?

**Comment by Christoph320** [comment]
Also: I don't know, how to link a css file to the cookie code. Am I really supposed to put the code inside the body tag in the header.php?

**Comment by Donsky-Osano** [comment]
@Christoph320 There are a lot of questions here I can't answer because I don't know your project structure but I can answer the question I think you've initially come here for:

-- v3 --
{
  // ...options,
  onInitialise: function ( status){
    // this is where you make decisions on your cookies based on the 'status' value
  },
  // or
  onStatusChange: function ( status ) {
    // this is where you make decisions on your cookies based on the 'status' value
  }
}
```

-- v4 --
```
cc.on( "initialized", statuses => {
  // this is where you make decisions on your cookies based on the 'statuses' value
})
cc.on( "statusChanged", ( cookieName,  status ) => {
  // This will fire once for each category, if ANY category value is changed or 'allow/deny' is selected for all
  // this is where you make decisions on your cookies based on the 'statuses' value
})
```

**Comment by Christoph320** [comment]
Hi, thank you very much. But **where** do I implement this code? I run a blog on Wordpress and don't want to paste it in the wrong file.

**Comment by Donsky-Osano** [comment]
That's up to you. We do not support any specific frameworks or libraries in favor of being totally agnostic. It's up to you where you want to implement this, when and how.

The docs are pretty thorough though, please check them out here:
https://cookieconsent.osano.com/documentation/about-cookie-consent/
